on:
    push:
        branches:
            - 'master'
    schedule:
        - cron: '0 0 * * *'


jobs:
    health-check:
        runs-on: ubuntu-20.04
        steps:
            - name: Check the status of the deployed website
              uses: jtalk/url-health-check-action@v3
              with:
                url: https://fullstackopenpokedex-9hfh.onrender.com/health